import type { Movies } from "../src/db";

export const data: Movies[] = [
  {
    title: "Boruto: Naruto The Movie",
    year: 2000,
    plot: "The spirited Boruto Uzumaki, son of Seventh Hokage Naruto, is a skilled ninja who possesses the same brashness and passion his father once had. However, the constant absence of his father, who is busy with his Hokage duties, puts a damper on Boruto's fire. He ends up meeting his father's friend Sasuke, and requests to become... his apprentice!? The curtain on the story of the new generation rises!",
    genres: [3, 1, 4],
    genre_names: ["Action", "Animation", "Comedy"],
    backdrop: "https://cdn.watchmode.com/backdrops/0158257_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=4RlEbHhuHPM",
    rating: "PG-13",
    views: 0,
  },
  {
    title: "Naruto Shippūden",
    plot: "Naruto Shippuuden is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as He has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.",
    year: 2007,
    genres: [3, 39, 40],
    genre_names: ["Action & Adventure", "Animation", "Sci-Fi & Fantasy"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/0383674_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=yKELA1qBAKA",
    views: 0,
  },
  {
    title: "Naruto",
    plot: "In another world, ninja are the ultimate power, and in the Village Hidden in the Leaves live the stealthiest ninja in the land. Twelve years earlier, the fearsome Nine-Tailed Fox terrorized the village and claimed many lives before it was subdued and its spirit sealed within the body of a baby boy. That boy, Naruto Uzumaki, has grown up to become a ninja-in-training who's more interested in pranks than in studying ninjutsu.. but Naruto is determined to become the greatest ninja ever!",
    year: 2002,
    genres: [3, 39, 40],
    genre_names: ["Action & Adventure", "Animation", "Sci-Fi & Fantasy"],
    rating: "TV-PG",
    backdrop: "https://cdn.watchmode.com/backdrops/0383672_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=yKELA1qBAKA",
    views: 0,
  },
  {
    title: "One Piece",
    plot: 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates. Monkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way. Luffy will do anything to get the One Piece and become King of the Pirates!',
    year: 1999,
    genres: [39, 4, 3],
    genre_names: ["Action & Adventure", "Animation", "Comedy"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/0388694_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=JvqcaQJgr-A",
    views: 0,
  },
  {
    title: "Twin Star Exorcists",
    plot: "Rokuro is from a family of exorcists, but he'd rather be a singer, a soccer player or anything but an exorcist! He's forced to own up to his own incredible potential when new arrival Benio stirs his competitive spirit. But their rivalry gets a twist when they earn the prestigious title of \"Twin Star Exorcists\"—two supreme fighters fated to marry and birth the ultimate spiritual warrior!",
    year: 2016,
    genres: [39, 4, 40, 1, 33, 9],
    genre_names: [
      "Action",
      "Action & Adventure",
      "Anime",
      "Comedy",
      "Fantasy",
      "Sci-Fi & Fantasy",
    ],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03136165_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=blD1-ekFg9U",
    views: 0,
  },
  {
    title: "Welcome to Demon School! Iruma-kun",
    plot: "Fourteen-year-old Suzuki Iruma has just been abandoned and sold to a demon by his irresponsible parents! Surprisingly, the next thing he knows he's living with the demon who has adopted him as his new grandson, and has been transferred into a school in the demon world where his new \"demon\" grandfather works as the principal. Thus begins the cowardly Iruma-kun's extraordinary school life among the otherworldly as he faces his true self, takes on challenges, and rises to become someone great.",
    year: 2019,
    genres: [3, 4, 40],
    genre_names: ["Animation", "Comedy", "Sci-Fi & Fantasy"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03165108_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=0BlyzLxFNss",
    views: 0,
  },
  {
    title: "My Hero Academia",
    plot: "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
    year: 2016,
    genres: [39, 3],
    genre_names: ["Action & Adventure", "Animation"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03175744_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=xQwdGV3ne4U",
    views: 0,
  },
  {
    title: "Chainsaw Man",
    plot: "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
    year: 2022,
    genres: [3, 39, 40, 4],
    rating: null,
    genre_names: [
      "Action & Adventure",
      "Animation",
      "Comedy",
      "Sci-Fi & Fantasy",
    ],
    backdrop: "https://cdn.watchmode.com/backdrops/03185315_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=HEwAiwttN10",
    views: 0,
  },
  {
    title: "Wakfu",
    plot: "Follow Yogu and his friends Amalia, Evangelyne, Tristepin, Ruel and Az as they try to rescue the world of Wakfu from destruction.",
    year: 2008,
    genres: [3, 39, 7, 40, 4],
    genre_names: [
      "Action & Adventure",
      "Animation",
      "Comedy",
      "Drama",
      "Sci-Fi & Fantasy",
    ],
    rating: "TV-Y7",
    backdrop: "https://cdn.watchmode.com/backdrops/03141719_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=Qs1Sst4f3yU",
    views: 0,
  },
  {
    title: "Hilda and the Mountain King",
    plot: "When Hilda wakes up in the body of a troll, she must use her wits and courage to get back home, become human again — and save the city of Trolberg.",
    year: 2021,
    genres: [3, 2, 9, 8, 38],
    genre_names: ["Adventure", "Animation", "Family", "Fantasy", "TV Movie"],
    rating: "TV-Y7",
    backdrop: "https://cdn.watchmode.com/backdrops/04155031_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=4MnjzxvsBNM",
    views: 0,
  },
  {
    title: "The Big Bang Theory",
    plot: "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    year: 2007,
    genres: [4],
    genre_names: ["Comedy"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03119408_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=U1KGRnWjllg",
    views: 0,
  },
  {
    title: "Chiquititas",
    plot: "Based on the original version of same name created by Cris Morena, the series tells the story of a group of orphans living in a manor, known as Raio de Luz, struggling and being guided by a young woman, Carol, that assumes a maternal figure for them. Their experiences such as discovering first love, deceptions, loneliness and friendship, as well as adventures in fantasy, are depicted throughout the series. The narrative is followed by musical themes and videoclips.",
    year: 2013,
    genres: [21, 8, 25],
    genre_names: ["Family", "Kids", "Soap"],
    rating: null,
    backdrop: "https://cdn.watchmode.com/backdrops/03179172_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=2Ukci9huBxM",
    views: 0,
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba - The Hashira Meeting Arc",
    plot: "Tanjiro and his sister Nezuko have been apprehended by the Demon Slayer Hashira, a group of extremely skilled swordfighters. Tanjiro undergoes trial for violating the Demon Slayer code, specifically smuggling Nezuko, a Demon, onto Mt. Natagumo. A recap film of Kimetsu no Yaiba, covering episodes 22-26 with some new footage and special ending credits.",
    year: 2020,
    genres: [3, 9],
    genre_names: ["Animation", "Fantasy"],
    rating: "PG-13",
    backdrop: "https://cdn.watchmode.com/backdrops/01637781_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=_Xwsa4iARp8",
    views: 0,
  },
  {
    title: "Sword Art Online: Progressive - Scherzo of Deep Night",
    plot: "Sword Art Online: Alicization (2018–19) Ref. Inside an unknown VR environment, Kirito spends his days as a child with his friends Eugeo and Alice. The three get lost in a cave in the outskirts of the Human Territory, ending up at the boundary of the Dark Territory.",
    year: 2022,
    genres: [3, 1, 9, 15],
    genre_names: ["Action", "Animation", "Fantasy", "Science Fiction"],
    rating: null,
    backdrop: "https://cdn.watchmode.com/backdrops/01694473_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=etMK4WKE48s",
    views: 0,
  },
  {
    title: "Sword Art Online",
    plot: "In the near future, a Virtual Reality Massive Multiplayer Online Role-Playing Game (VRMMORPG) called Sword Art Online has been released where players control their avatars with their bodies using a piece of technology called Nerve Gear. One day, players discover they cannot log out, as the game creator is holding them captive unless they reach the 100th floor of the game's tower and defeat the final boss. However, if they die in the game, they die in real life. Their struggle for survival starts now...",
    year: 2012,
    genres: [3, 40, 39],
    genre_names: ["Action & Adventure", "Animation", "Sci-Fi & Fantasy"],
    rating: "TV-MA",
    backdrop: "https://cdn.watchmode.com/backdrops/03114754_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=cdezBN2V34o",
    views: 0,
  },
  {
    title: "Sword Art Online Alternative: Gun Gale Online",
    plot: "A shy university student in Tokyo, Karen Kohiruimaki stands in stark contrast to her in-game avatar—in fact, she happens to stand above everyone else too, much to her dismay. Towering above all the people around her, Karen's insecurities over her height reach the point where she turns to the virtual world for an escape. Starting game after game in hopes of manifesting as a cute, short character, she finally obtains her ideal self in the world of Gun Gale Online. Overjoyed by her new persona, she pours her time into the game as LLENN, garnering her reputation as the legendary player killer. However, when one of LLENN's targets gets the best of her, she ends up meeting Pitohui, a skilled yet eccentric woman. Pitohui insists that LLENN participates in Squad Jam, a battle royale. Thrust into the heated competition, LLENN must fight with all her wit and will if she hopes to shoot her way to the top.",
    year: 2018,
    genres: [39, 40, 1, 33],
    genre_names: ["Action", "Action & Adventure", "Anime", "Sci-Fi & Fantasy"],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03114757_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=tULaW49codU",
    views: 0,
  },
  {
    title: "Arcane",
    plot: "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    year: 2021,
    genres: [3, 40, 39, 7],
    genre_names: [
      "Action & Adventure",
      "Animation",
      "Drama",
      "Sci-Fi & Fantasy",
    ],
    rating: "TV-14",
    backdrop: "https://cdn.watchmode.com/backdrops/03178198_bd_w780.jpg",
    video: "https://www.youtube.com/watch?v=F5tSoaJ93ac",
    views: 0,
  },
  {
    title: "One Punch Man",
    plot: 'Live-action feature adaptation of the well-known manga "One Punch Man".',
    year: null,
    genres: [1, 2, 9],
    genre_names: ["Action", "Adventure", "Fantasy"],
    rating: null,
    backdrop: "https://images.alphacoders.com/741/741098.jpg",
    video: "https://youtu.be/kErJOepkDQk",
    views: 0,
  },
];
